---
title: "Assignment 2"
authors: "Tony Nguyen, Jane Nguyen, Shiyuan Zhang, Naveed Aamir"
date: "2023-06-07"
output: html_document
---

```{r setup, include = FALSE}

# added libraries to potentially use 
library(ISLR)
library(MASS)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(gganimate)
library(ggrepel)
library(dplyr)
library(tidyverse)
library(ggmap)
library(maps)
library(mapdata) 
library(knitr)
library(kableExtra)
library(countrycode)

knitr::opts_chunk$set(echo = TRUE)

```


```{r, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}

# read in data set 
data = read.csv('Merge_all_2010_2020_updated.csv')

```


```{r, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}

# extracting columns to use from data 
extractedData =  data[, c(1, 2, 3, 12)]

# omit NA values
newExtractedData = na.omit(extractedData)

# head of data 
extractedDataHead = head(newExtractedData)

```

---

**Variable Class** 

```{r, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}

# get classes from extracted data  
extractedDataClass = names(newExtractedData)

extractedDataClasses = data.frame(Variables = extractedDataClass)

# display classes using kable()
kable(extractedDataClasses, format = "html", align = "c") %>% kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE)

```


---

**Summary Table** 

```{r, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}

# 2000 data
y2000 = newExtractedData[newExtractedData $ Year == 2000, ]

year2000Total = summary(y2000 $ Total_alcohol_consumption_per_capita)

year2000TotalArray = as.array(year2000Total)

year2000TotalData = data.frame(Statistics = rownames(year2000TotalArray), Values = year2000TotalArray, stringsAsFactors = FALSE)


# 2005 data
y2005 = newExtractedData[newExtractedData $ Year == 2005, ]

year2005Total = summary(y2005 $ Total_alcohol_consumption_per_capita)

year2005TotalArray = as.array(year2005Total)

year2005TotalData = data.frame(Statistics = rownames(year2005TotalArray), Values = year2005TotalArray, stringsAsFactors = FALSE)


# 2010 data
y2010 = newExtractedData[newExtractedData $ Year == 2010, ]

year2010Total = summary(y2010 $ Total_alcohol_consumption_per_capita)

year2010TotalArray = as.array(year2010Total)

year2010TotalData = data.frame(Statistics = rownames(year2010TotalArray), Values = year2010TotalArray, stringsAsFactors = FALSE)


# 2015 data
y2015 = newExtractedData[newExtractedData $ Year == 2015, ]

year2015Total = summary(y2015 $ Total_alcohol_consumption_per_capita)

year2015TotalArray = as.array(year2015Total)

year2015TotalData = data.frame(Statistics = rownames(year2015TotalArray), Values = year2015TotalArray, stringsAsFactors = FALSE)


# 2018 data
y2018 = newExtractedData[newExtractedData $ Year == 2018, ]

year2018Total = summary(y2018 $ Total_alcohol_consumption_per_capita)

year2018TotalArray = as.array(year2018Total)

year2018TotalData = data.frame(Statistics = rownames(year2018TotalArray), Values = year2018TotalArray, stringsAsFactors = FALSE)


# combining columns 
totalCombinedSummary = cbind(year2000TotalData$Statistics, year2000TotalData$Values.Freq, year2005TotalData$Values.Freq, year2010TotalData$Values.Freq, year2015TotalData$Values.Freq, year2018TotalData$Values.Freq)

# renaming columns 
colnames(totalCombinedSummary) = c("Statistics", "2000", "2005", "2010", "2015", "2018")

# presenting using kable()
kable(totalCombinedSummary, format = "html", align = "c") %>% kable_styling(bootstrap_options = c("striped", "hover"), full_width = FALSE)

```


---

**Figure 1** 

```{r, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}

# loading world map 
worldMap = map_data("world")

# selecting specific year 2018
extractedData2018 = filter(newExtractedData, Year == 2018)

worldMap $ iso3c = countrycode(worldMap$region, 'country.name', 'iso3c')

extractedData2018Map = left_join(worldMap, extractedData2018, by = c("iso3c" = "Code"))

# heat map based on total alcohol consumption in 2018 
dataMap = ggplot() + geom_map(data = extractedData2018Map, map = extractedData2018Map, aes(x = long, y = lat, map_id = region, fill = Total_alcohol_consumption_per_capita), color = "black") + coord_equal() + theme_void() + scale_fill_gradient2(low = "white", mid = "lightblue", high = "darkred", name = "Alcohol Consumed (Litres)") + labs(title = "2018 Alcohol Consumption per Capita")

dataMap

```


---

**Figure 2** 

```{r, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}

# filtering extracted data by total alcohol consumption in 2018
topCountryExtractedData2018 = extractedData2018 %>% group_by(Entity) %>% summarize(Total = sum(Total_alcohol_consumption_per_capita))

# arranging countries in alphabetical order
topCountryExtractedData2018 = arrange(topCountryExtractedData2018, desc(Total))

# grabbing the top 20 countries 
topCountryExtractedData2018 = head(topCountryExtractedData2018, 20)

# bar chart of the top 20 countries of alcohol consumption in 2018 
top20Bar = ggplot(topCountryExtractedData2018, aes(x = Entity, y = Total, color = Entity)) + geom_bar(stat = "identity", fill = "white") + labs(title = "Top 20 Countries by Alcohol Consumption in 2018", x = "Countries", y = "Alcohol Consumed (Litres)") + theme_minimal() + scale_x_discrete(guide = guide_axis(angle = 30)) + theme(legend.position = "none")

top20Bar

```

